config/routes.rb
Rails.application.routes.draw do
  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  root "pages#home"
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 6, maximum: 500}
  validates :author, presence: true, length: {minimum: 4, maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
     # @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article =Article.new
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated."
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def set_article
  @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :author)
  end

end




















# class ArticlesController < ApplicationController
#   before_action :set_article, only: %i[ show edit update destroy ]
#
#   # GET /articles or /articles.json
#   def index
#     @articles = Article.all
#   end
#
#   # GET /articles/1 or /articles/1.json
#   def show
#   end
#
#   # GET /articles/new
#   def new
#     @article = Article.new
#   end
#
#   # GET /articles/1/edit
#   def edit
#   end
#
#   # POST /articles or /articles.json
#   def create
#     @article = Article.new(article_params)
#
#     respond_to do |format|
#       if @article.save
#         format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
#         format.json { render :show, status: :created, location: @article }
#       else
#         format.html { render :new, status: :unprocessable_entity }
#         format.json { render json: @article.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # PATCH/PUT /articles/1 or /articles/1.json
#   def update
#     respond_to do |format|
#       if @article.update(article_params)
#         format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
#         format.json { render :show, status: :ok, location: @article }
#       else
#         format.html { render :edit, status: :unprocessable_entity }
#         format.json { render json: @article.errors, status: :unprocessable_entity }
#       end
#     end
#   end
#
#   # DELETE /articles/1 or /articles/1.json
#   def destroy
#     @article.destroy
#
#     respond_to do |format|
#       format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_article
#       @article = Article.find(params[:id])
#     end
#
#     # Only allow a list of trusted parameters through.
#     def article_params
#       params.require(:article).permit(:title, :description, :author)
#     end
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= article.author %>
  </p>

</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>Here are some errors</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %> <br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>


<p><%= link_to 'Back', articles_path %></p>



<%#= form_with(model: article) do |form| %>
  <%# if article.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>-->

<!--      <ul>-->
        <%# article.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div>-->
    <%#= form.label :title, style: "display: block" %>
    <%#= form.text_field :title %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :description, style: "display: block" %>
    <%#= form.text_area :description %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :author, style: "display: block" %>
    <%#= form.text_field :author %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>


<%# if @article.errors.any? %>
<!--  <h2>Here are some errors</h2>-->
<!--  <ul>-->
    <%# @article.errors.full_messages.each do |msg| %>
<!--      <li>-->
        <%#= msg %>
<!--      </li>-->
    <%# end %>
<!--  </ul>-->
<%# end %>

<%#= form_with(model: @article, local: true) do |f| %>

<!--  <p>-->
<!--    <%#= f.label :title %> <br>-->
    <%#= f.text_field :title %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= f.label :author %> <br>-->
    <%#= f.text_field :author %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= f.label :description %> <br>-->
    <%#= f.text_area :description %>
<!--  </p>-->

<!--  <p>-->
    <%#= f.submit %>
<!--  </p>-->

<%# end %>


<!--<p><%#= link_to 'Back', articles_path %></p>-->































<%#= render "form", article: @article %>

<!--<br>-->

<!--<div>-->
<!--  <%#= link_to "Show this article", @article %> |-->
  <%#= link_to "Back to articles", articles_path %>
<!--</div>-->

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<!--<h1><%#= render @articles %></h1>-->

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= article.author %></td>
      <td><%= link_to 'Show', article %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to "Delete", article_path(article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2><%= link_to 'Create new article', new_article_path %></h2>

<p><%= link_to 'Go to home page', root_path %></p>




































<!--<p style="color: green"><%#= notice %></p>-->

<!--<h1>Articles</h1>-->

<!--<div id="articles">-->

<!--    <table>-->
<!--      <thead>-->
<!--      <tr>-->
<!--        <th>Title</th>-->
<!--        <th>Description</th>-->
<!--        <th>author</th>-->
<!--        <th>Actions</th>-->
<!--      </tr>-->
<!--      </thead>-->
<!--      <tbody>-->
      <%# @articles.each do |article| %>
<!--      <tr>-->
<!--        <td><%#= article.title %></td>-->
<!--        <td><%#= article.description %></td>-->
<!--        <td><%#= article.author %></td>-->
<!--        <td><%#= link_to "Show", article %></td>-->
<!--        <td><%#= link_to "Edit", edit_article_path(article) %></td>-->
<!--        <td><%#= link_to "Destory", article, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>-->
<!--        <br>-->
<!--      </tr>-->
      <%# end %>
<!--      </tbody>-->
<!--    </table>-->
<!--</div>-->

<%#= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>


<%# if @article.errors.any? %>
<!--  <h2>Here are some errors</h2>-->
<!--  <ul>-->
    <%# @article.errors.full_messages.each do |msg| %>
<!--      <li>-->
        <%#= msg %>
<!--      </li>-->
    <%# end %>
<!--  </ul>-->
<%# end %>

<%#= form_with scope: :article, url: articles_path, local: true do |f| %>

<!--  <p>-->
<!--    <%#= f.label :title %> <br>-->
    <%#= f.text_field :title %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= f.label :author %> <br>-->
    <%#= f.text_field :author %>
<!--  </p>-->

<!--  <p>-->
<!--    <%#= f.label :description %> <br>-->
    <%#= f.text_area :description %>
<!--  </p>-->

<!--  <p>-->
    <%#= f.submit %>
<!--  </p>-->

<%# end %>


<!--<p><%#= link_to 'Back', articles_path %></p>-->






















<!--<h1>New article</h1>-->

<%#= render "form", article: @article %>

<!--<br>-->

<!--<div>-->
  <%#= link_to "Back to articles", articles_path %>
<!--</div>-->

app/views/articles/show.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<%#= render @article %>

<!--<div>-->
<!--  <%#= link_to "Edit", edit_article_path(@article) %> |-->
  <%#= link_to "Back", articles_path %>

  <%#= button_to "Destroy this article", @article, method: :delete %>
<!--</div>-->

<h1><strong>showing article details</strong></h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>Author: </strong><%= @article.author %></p>
<p><%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to "Delete", @article, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
<br>
<p><%= link_to 'Back', articles_path %></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<%  end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is About Page</h1>

<p><%= link_to 'Return to article page', articles_path %></p>

<p><%= link_to 'Return to home page', root_path %></p>

app/views/pages/home.html.erb
<h1>This is Home Page</h1>

<p><%= link_to 'Return to article page', articles_path %></p>

<p><%= link_to 'Go to about page', about_path %></p>